// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akudeivyicdyiycogytg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrdWRlaXZ5aWNkeWl5Y29neXRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODI4NzYsImV4cCI6MjA3MjU1ODg3Nn0.HC2uUw50TUY0YvHmIaqSMA7Ihz8fdfOULQJFEHGhClg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});